config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users
  
  resources :events
  resources :articles
  resources :clients
  resources :dashboard
  
  get '/about', :to => 'pages#about', :as => 'about'
  get '/faq', :to => 'pages#faq', :as => 'faq'
  get '/contact', :to => 'pages#contact', :as => 'contact'
  get '/amortization', :to => 'pages#amortization', :as => 'amortization'
  get '/about_us', :to => 'pages#about_us', :as => 'about_us'
  
  root :to => 'pages#home'
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user

	after_create :fetch_details

	def fetch_details
		self.send("fetch_details_from_#{self.provider.downcase}")
	end


	def fetch_details_from_facebook
		graph = Koala::Facebook::API.new(self.token)
		facebook_data = graph.get_object("me")
		self.username = facebook_data['username']
		self.save
	end

	def fetch_details_from_twitter

	end


	def fetch_details_from_github
	end


	def fetch_details_from_linkedin

	end

	def fetch_details_from_google_oauth2

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  validates :name, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true, numericality: true

  mount_uploader :image, ImageUploader
  has_many :authorizations
  
  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user || User.where('email = ?', auth["info"]["email"]).first
      if user.blank?
        user = User.new
        user.password = Devise.friendly_token[0,10]
        user.name = auth.info.name
        user.email = auth.info.email
       
        if auth.provider == "twitter" 
          user.save(validate: false) 
        else
          user.save
        end
      end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
    end
   authorization.user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "dashboard"
    else
      "application"
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def index
  end

  def show
  end

  def new
  end

  def create
    password = Devise.friendly_token.first(8)
  
   # user = User.create!(:email => email, :password => generated_password)
   # RegistrationMailer.welcome(user, generated_password).deliver
    
    @client = User.new(client_params.merge(:password => password, :password_confirmation => password))
    
    respond_to do |format|
       if verify_recaptcha(model: @client) && @client.save
         format.html { redirect_to @client, notice: 'Thing was successfully created.' }
         #format.json { render action: 'show', status: :created, location: @client }
         format.js { render json: @client, content_type: 'text/json',  status: :ok }
       else
         format.html { render action: 'new' }
         #format.json { render json: @client.errors, status: :unprocessable_entity }
         format.js { render json: @client.errors.full_messages, status: :unprocessable_entity }
       end
     end
  end

  def update
  end

  def destroy
  end
  
  private
  
  def client_params
    params.require(:client).permit(:name, :email, :phone)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	skip_before_filter :authenticate_user!
	
	def all
		p env["omniauth.auth"]
		user = User.from_omniauth(env["omniauth.auth"], current_user)
		if user.persisted?
			flash[:notice] = "You are in..!!! Go to edit profile to see the status for the accounts"
			sign_in_and_redirect(user)
		else
			session["devise.user_attributes"] = user.attributes
			redirect_to new_user_registration_url
		end
	end

	def failure
		super
	end


	alias_method :facebook, :all
	alias_method :twitter, :all
	alias_method :passthru, :all
	alias_method :google_oauth2, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @client = User.new
  end
  
  def faq
  end
  
  def amortization
  end
  
  def location
  end
  
  def about_us
  end
  
  def contact
    @client = User.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
    private
    
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]
  
  def index
     @users = User.all
  end

  def show
  end

  def new
  end

  def create
    @client = User.new(client_params)
    
    if verify_recaptcha(model: @client) && @client.save
      @client.client = request
    end
 
  end

  def update
    if @user.update_attributes(client_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
  end
  
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end
    
  def client_params
    params.require(:user).permit(:name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/index.html.erb
<h1>Clients#index</h1>
<p>Find me in app/views/clients/index.html.erb</p>

app/views/clients/new.html.erb
<h1>Clients#new</h1>
<p>Find me in app/views/clients/new.html.erb</p>

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<p>Find me in app/views/clients/show.html.erb</p>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>

app/views/dashboard/index.html.erb
<div class="container">
  <h2>Dashboard</h2>
  <p>List of clients:</p>            
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
        <td>Pending</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
        <td>Confirmed</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
        <td>Close</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :required => true, :autofocus => true %>
    <%= f.input :email, :required => true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<div>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<section>
    <div class="container">
        <div class="row account-wall">
        
            <div class="col-sm-12">

                <h2>Edit Profile</h2>
                
                <%= simple_form_for(@user, html: { method: :put, class: "form-signin" }) do |f| %>
                  <%= f.error_notification %>

                  <div class="form-group">
                    <input type="name" value="<%= @user.name %>" name="user[name]" class="form-control" placeholder="Name" required autofocus>
                  </div>
                
                  <div class="form-group">
                    <input type="email" value="<%= @user.email %>" name="user[email]" class="form-control" placeholder="Email" required>
                </div>
                <div class="form-group">
                    <input type="password" name="user[password]" class="form-control" placeholder="Password" required>
                    <span class="hint">leave it blank if you don't want to change it</span><br>
                 </div>
                  <div class="form-group">
                    <input type="password" id="user_password_confirmation" name="user[password_confirmation]" placeholder="Password confirmation" class="form-control">
                 </div>
                 <div class="form-group">
                    <input type="password" id="user_current_password" name="user[current_password]" class="form-control" placeholder="Current password">
                    <span class="hint">we need your current password to confirm your changes</span><br>
                  </div>
                
                  <div class="form-group">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
                  </div>
                <% end %>
                
            <div class="col-sm-12 panel-footer">
                <h3>Cancel my account</h3>
                
                <p>Unhappy? <%= link_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></p>
                
                <%= link_to 'Show', @user %>
            </div>
                
            </div>
        </div>
    </div>
</section>

<!--https://www.youtube.com/watch?v=s09NJvm6VCM-->

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<section>
    <div class="container">
        <div class="row account-wall">
        
            <div class="col-sm-12">

                <p id="notice"><%= notice %></p>
                
                <p>
                  <strong>Name:</strong>
                    <%= @user.name %>
                </p>
                <br>
                <p>
                  <strong>Email:</strong>
                    <%= @user.email %>
                </p>
                
                <%= link_to 'Edit', edit_user_path(@user) %>
                
            </div>
        </div>
    </div>
</section>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>