config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks" }
  resources :users
  
  resources :events
  resources :articles
  resources :clients
  resources :dashboard
  
  get '/about', :to => 'pages#about', :as => 'about'
  get '/faq', :to => 'pages#faq', :as => 'faq'
  get '/contact', :to => 'pages#contact', :as => 'contact'
  get '/amortization', :to => 'pages#amortization', :as => 'amortization'
  get '/about_us', :to => 'pages#about_us', :as => 'about_us'
  
  root :to => 'pages#home'
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user

	after_create :fetch_details

	def fetch_details
		self.send("fetch_details_from_#{self.provider.downcase}")
	end


	def fetch_details_from_facebook
		graph = Koala::Facebook::API.new(self.token)
		facebook_data = graph.get_object("me")
		self.username = facebook_data['username']
		self.save
	end

	def fetch_details_from_twitter

	end


	def fetch_details_from_github
	end


	def fetch_details_from_linkedin

	end

	def fetch_details_from_google_oauth2

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  validates :name, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true, numericality: true

  mount_uploader :image, ImageUploader
  has_many :authorizations
  
  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user || User.where('email = ?', auth["info"]["email"]).first
      if user.blank?
        user = User.new
        user.password = Devise.friendly_token[0,10]
        user.name = auth.info.name
        user.email = auth.info.email
       
        if auth.provider == "twitter" 
          user.save(validate: false) 
        else
          user.save
        end
      end
     authorization.username = auth.info.nickname
     authorization.user_id = user.id
     authorization.save
    end
   authorization.user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "dashboard"
    else
      "application"
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def index
  end

  def show
  end

  def new
  end

  def create
    password = Devise.friendly_token.first(8)
  
   # user = User.create!(:email => email, :password => generated_password)
   # RegistrationMailer.welcome(user, generated_password).deliver
    
    @client = User.new(client_params.merge(:password => password, :password_confirmation => password))
    
    respond_to do |format|
       if verify_recaptcha(model: @client) && @client.save
         format.html { redirect_to @client, notice: 'Thing was successfully created.' }
         #format.json { render action: 'show', status: :created, location: @client }
         format.js { render json: @client, content_type: 'text/json',  status: :ok }
       else
         format.html { render action: 'new' }
         #format.json { render json: @client.errors, status: :unprocessable_entity }
         format.js { render json: @client.errors.full_messages, status: :unprocessable_entity }
       end
     end
  end

  def update
  end

  def destroy
  end
  
  private
  
  def client_params
    params.require(:client).permit(:name, :email, :phone)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  def index
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @client = User.new
  end
  
  def faq
  end
  
  def amortization
  end
  
  def location
  end
  
  def about_us
  end
  
  def contact
    @client = User.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
    private
    
    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :set_user, only: [:show, :edit, :update]
  before_filter :validate_authorization_for_user, only: [:edit, :update]
  
  def index
     @users = User.all
  end

  def show
  end

  def new
  end

  def create
    @client = User.new(client_params)
    
    if verify_recaptcha(model: @client) && @client.save
      @client.client = request
    end
 
  end

  def update
    if @user.update_attributes(client_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
  end
  
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def validate_authorization_for_user
       redirect_to root_path unless @user == current_user
    end
    
  def client_params
    params.require(:user).permit(:name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-error"
    when :alert then "alert alert-error"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12">
					<div class="footer">
						<div class="row">
							<!--<div class="col-xs-12 col-lg-3 col-md-3 col-sm-3">-->
							<!--	<div class="news-letter">-->
       <!--           <h2>DWBH Lending Investors</h2>-->
       <!--              <p style="text-align: justify; ">We offer mainly "Speedy and Easy" secured loans to the middle emerging market with the objective of providing them with immediate and easy solutions to yout financial needs.</p>-->
							<!--	</div>-->
							<!--</div>-->

							<div class="col-lg-6">
								<div class="footer-menu-area">
									<div class="footer-menu">
										<ul>
											<li><a href="/#services">Loan Services</a></li>
											<li><a href="/#calculator">Loan Calculator</a></li>
											<li><%= link_to 'Contact Us', contact_path  %></li>
											<li><%= link_to 'About Us', about_us_path  %></li>
										</ul>
									</div>
									<div class="footer-menu">
										<ul>
											<li><%= link_to 'Help & Inquiries', faq_path %></li>
											<li><a href="#">Download Forms</a></li>
											<li><a href="#">Privacy Policy</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="col-lg-6">
								<div class="col-lg-6"> 
									<h4>Contact Sales</h4>
									<p>
										<span class="glyphicon glyphicon-phone"></span> (+63) 917-632-1775<br>
										<span class="glyphicon glyphicon-phone"></span> (+63) 922-827-0868<br>
								  	<span class="glyphicon glyphicon-phone-alt"></span> (032) 253-5407 <br>
								  	<span class="glyphicon glyphicon-phone-alt"></span> (032) 253-4901</p>
								  </p>
								</div>
								<div class="col-lg-6"> 
									<h4>General Inquiries</h4>
									<a href="mailto:dwbh.marketing@gmail.com">dwbh_hr@yahoo.com </a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom-area" style="text-align: center">
				<div class="fb-follow" data-href="https://www.facebook.com/dwbh.lending.5" data-layout="standard" data-show-faces="true"></div>
			</div>
			<div class="footer-bottom-area">
				<div class="row">
					<div class="col-xs-12 col-lg-6 col-md-6 col-sm-6">
						<div class="copyright">
							<p>&copy; 2015 <%= link_to "DWBH Lending Investors, Inc. ", root_url %> All rights reserved.</p>
						</div>
					</div>
					<div class="col-xs-12 col-lg-6 col-md-6 col-sm-6">
						<div class="footer-payment-logo">
							
				                <ul class="list-inline">
				                    <li>
				                        <a href="https://www.facebook.com/DWBH-100165668043309" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
				                    </li>
				                    <!--<li>-->
				                    <!--    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>-->
				                    <!--</li>-->
				                    <li>
				                        <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
				                    </li>
				                    <li>
				                        <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
				                    </li>
				                    <!--<li>-->
				                    <!--    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>-->
				                    <!--</li>-->
				                </ul>
						</div>
					</div>
				</div>
			</div>
		</div>
</footer>

app/views/layouts/_header.html.erb
<header class="header-section section section-dark navbar navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header navbar-left page-scroll" >
      <!-- RESPONSIVE MENU BUTTON -->
        <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <nav id="navigation" class="navbar-left">
          <%= link_to root_path, :class => 'navbar-brand' do %>
            <%= image_tag "dwbh.png" %>
            <span class="log-text">Lending Investors</span>
          <% end %>
        </nav> 
        <nav id="navigation" class="navigation navbar-collapse navbar-right collapse" aria-expanded="false" style="height: 81px; ">
           <p class="navbar-text"><span class="glyphicon glyphicon-time"></span> Mon-Sat 8:30am - 5:30pm</p>
           <p class="navbar-text"><span class="glyphicon glyphicon-phone"></span> Globe 0917-632-1775, Sun 0922-827-0868</p>
           <p class="navbar-text"><span class="glyphicon glyphicon-phone-alt"></span> (032) 253-5407, (032) 253-4901</p>
        </nav> 
    </div>

    <nav id="navigation" class="navigation navbar-collapse navbar-right collapse" aria-expanded="false" style="height: 81px; ">
      <ul class="nav navbar-nav navbar-right nav-menu-padding-top">
        <!--<li class="page-scroll "><%= link_to 'Home', '/#header', class: "#{action_name == "home" ? "active" : nil}"  %></li>-->
        
        <li class="dropdown" role="presentation">
          <a aria-expanded="false" aria-haspopup="true" role="button" href="#" data-toggle="dropdown" class="dropdown-toggle">
            Loan Services<span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Loan Products', '/#services' %></li>
            <li><%= link_to 'Monthly Amortization', amortization_path %></li>
          </ul>
        </li>
        
        <li class="page-scroll >"><%= link_to 'Loan Calculator',  "/#calculator", class: "#{action_name == "calculator" ? "active" : nil}"  %></li>
        <li class="page-scroll "><%= link_to 'Contact Us', contact_path, class: "#{action_name == "contact" ? "active" : nil}"  %></li>
        <li class="page-scroll "><%= link_to 'F.A.Q', faq_path, class: "#{action_name == "faq" ? "active" : nil}"  %></li>
            
        <% if user_signed_in? %>

          <li class="dropdown" role="presentation">
            <a aria-expanded="false" aria-haspopup="true" role="button" href="#" data-toggle="dropdown" class="dropdown-toggle">
              My Account<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Loans', '#' %></li>
              <li class="divider" role="separator"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path %></li>
            </ul>
          </li>
          

        <% else %>
<!--          <li><%= link_to 'Sign Up', new_user_registration_path %></li>-->
          <li><%= link_to 'Sign In', new_user_session_path, class: "#{action_name == "new" ? "active" : nil}" %></li>
        <% end %>

      </ul>
    </nav>    

  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="ft0kmV3FSVwO5tfwidz6HCZF3nojOmoIru6GLt7HiHg" />
    <meta property="fb:admins" content="100000251664444" />
	<meta name="copyright" content="2015 Copyright www.dwbhlending.com">
	<meta name="language" content="English">
	<meta name="Rating" content="General">
	<meta name="expires" content="never">
	<meta name="author" content="Author:dwbhlending.com">
	<meta name="email" content="Email: dwbh.marketing@gmail.com">
	<meta content="Need Fast Cash? We offer loans as low as 1.5% - 3% for Car, Home, Business, OFW, Salary, and other loan types. Lending in Cebu Philippines." name="description">
	<meta content="Cebu Lending, Cebu Financing, cebu quick loans, cebu fast loans, cash loans, lending company, lending companies, cebu lending company, easy loans, salary loan, ofw loan, lending, I want a loan, personal loans, personal loan online, instant loan, online loan application, collateral loan, cebu fast lending, loan cebu, non-collateral,Real Estate Mortgage, Chattel Mortgage, Car, Home, Business, OFW, Salary" name="keywords">
	
	<meta property="fb:app_id"             content="545268678973039"/>
	<meta property="og:url"                content="http://www.dwbhlending.com" />
	<meta property="og:type"               content="product.group" />
	<meta property="og:title"              content="Need an easy and fast Cash?" />
	<meta property="og:description"        content="DWBH lending Investors offer mainly Speedy and Easy secured loans from Car, Home, Business, OFW, Salary and other loan types in Cebu City." />
	<meta property="og:image"              content="http://www.dwbhlending.com/assets/feature1-b2e02b3ef6a08adbf6ec0ed7bb3b1d53189b84f461759f4edb78335e25d3966f.jpg" />

    <%= display_meta_tags :site => "DWBH Lending Investors | Real Estate Mortgage, Chattel Mortgage, Car, Home, Business, OFW, Salary etc.", :reverse => true %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <link href="assets/dwbh-icon-4131070134febfde4754720505abb0c828bdb78e430fccfc60244fc7cec3baa0.png" rel="shortcut icon">
  </head>
  <body>

     <%= render 'layouts/header' %>
  
    <%= yield %>
<!--
    <%= action_name %>
    <%= debug(params) if Rails.env.development? %>
-->
      <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<!--    <div class="scroll-top page-scroll visible-xs visble-sm">-->


       <!--  <a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647; display: block;"><i class="fa fa-angle-up"></i></a> -->

        
<!--    </div>-->
    <%= render 'layouts/footer' %>

     <%= javascript_include_tag "application" %>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    
    <%= yield :scripts %>
  </body>

    <script type="text/javascript">
      // start accrue.js
    (function($){

        $(document).ready(function(){

          // set up normal loan calculation
          //$(".calculator-box").accrue();

        });
      
	/***************** Nav Transformicon ******************/

	/* When user clicks the Icon */
	$('.nav-toggle').click(function() {
		$(this).toggleClass('active');
		$('.header-nav').toggleClass('open');
		event.preventDefault();
	});
	/* When user clicks a link */
	$('.header-nav li a').click(function() {
		$('.nav-toggle').toggleClass('active');
		$('.header-nav').toggleClass('open');

	});

	/***************** Header BG Scroll ******************/

	$(function() {
		$(window).scroll(function() {
			var scroll = $(window).scrollTop();

			if (scroll >= 20) {
				// $('section.navigation').addClass('fixed');
				// $('header').css({
				// 	"border-bottom": "none",
				// 	"padding": "20px 0"
				// });
				// $('header .member-actions').css({
				// 	"top": "26px",
				// });
				// $('header .navicon').css({
				// 	"top": "34px",
				// });
			} else {
				$('section.navigation').removeClass('fixed');
				$('header').css({
					"border-bottom": "solid 1px rgba(255, 255, 255, 0.2)",
					"padding": "0"
				});
				$('header .member-actions').css({
					"top": "41px",
				});
				$('header .navicon').css({
					"top": "48px",
				});
			}
		});
	});
	/***************** Smooth Scrolling ******************/

	$(function() {

		$('a[href*=#]:not([href=#])').click(function() {
			if (location.pathname.replace(/^\//, '') === this.pathname.replace(/^\//, '') && location.hostname === this.hostname) {

				var target = $(this.hash);
				target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
				if (target.length) {
					$('html,body').animate({
						scrollTop: target.offset().top
					}, 2000);
					return false;
				}
			}
		});

	});
      
    $("[rel='tooltip']").tooltip();    
 
    $('.product-thumbnail').hover(
        function(){
            $(this).find('.caption').slideDown(100); //.fadeIn(250)
        },
        function(){
            $(this).find('.caption').slideUp(100); //.fadeOut(205)
        }
    ); 
      
      $('#myTabs a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
      })
        
     })(jQuery); 
      
      


  </script>
  
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	
	  ga('create', 'UA-70607284-1', 'auto');
	  ga('send', 'pageview');
	
	</script>
 
    <script src="//code.jquery.com/ui/1.10.4/jquery-ui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
 
 <script>
      $(document).ready(function() {
          $("#slider").slider({
              range: "min",
              animate: true,
              value:1,
              min: 5000,
              max: 1000000,
              step: 10,
              slide: function(event, ui) {
                update(1,ui.value); //changed
              }
          });

          $("#slider2").slider({
              range: "min",
              animate: true,
              value:1,
              min: 1,
              max: 48,
              step: 1,
              slide: function(event, ui) {
                update(2,ui.value); //changed
              }
          });
          

          //Added, set initial value.
          $("#amount").val(5000);
          $("#duration").val(1);
          $("#amount-label").text(5000);
          $("#duration-label").text(1);
          
          $('#myForm input').on('change', function() {
			   update(); 
			});

         
          update();
      });

          $('#myFormResult input').on('keyup', function() {
               $( "#amount" ).val($("#amount").val());
               $( "#duration" ).val($("#duration").val());
			   update(); 
			});
         
      //changed. now with parameter
      function update(slider,val) {
        //changed. Now, directly take value from ui.value. if not set (initial, will use current value.)
        var $amount = slider == 1?val:$("#amount").val();
        var $duration = slider == 2?val:$("#duration").val();
        var $interest = $('input[name=interest]:checked', '#myForm').val() == undefined ? $("#interest").val() : $('input[name=interest]:checked', '#myForm').val();

        /* commented
        $amount = $( "#slider" ).slider( "value" );
        $duration = $( "#slider2" ).slider( "value" );
         */
         
         $interest_amount = (parseInt($amount)+((parseInt($amount) * parseFloat($interest))*$duration));
         $interest_amount_total = "₱" + Math.round($interest_amount/$duration).toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,');
         
         //$total = "P" + ($amount * $duration);
         $( "#amount" ).val(parseFloat($amount));
         $( "#amount-label" ).text($amount);
         $( "#duration" ).val($duration);
         $( "#duration-label" ).text($duration);
         $( "#total" ).val($interest_amount_total);
         $( "#total-label" ).text($interest_amount_total);

         $('#slider a').html('<label><span class="glyphicon glyphicon-chevron-left"></span> '+$amount+' <span class="glyphicon glyphicon-chevron-right"></span></label>');
         $('#slider2 a').html('<label><span class="glyphicon glyphicon-chevron-left"></span> '+$duration+' <span class="glyphicon glyphicon-chevron-right"></span></label>');

      }

    </script>

    <script>
      var div = document.createElement('div');
      div.className = 'fb-customerchat';
      div.setAttribute('page_id', '100165668043309');
      div.setAttribute('ref', 'b64:bGl2ZS1jaGF0');
      document.body.appendChild(div);
      window.fbMessengerPlugins = window.fbMessengerPlugins || {
        init: function () {
          FB.init({
            appId            : '1678638095724206',
            autoLogAppEvents : true,
            xfbml            : true,
            version          : 'v3.0'
          });
        }, callable: []
      };
      window.fbAsyncInit = window.fbAsyncInit || function () {
        window.fbMessengerPlugins.callable.forEach(function (item) { item(); });
        window.fbMessengerPlugins.init();
      };
      setTimeout(function () {
        (function (d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) { return; }
          js = d.createElement(s);
          js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk/xfbml.customerchat.js";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
      }, 0);
    </script>


</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="fb:admins" content="100000251664444" />
    <%= display_meta_tags :site => ENV['title'], :reverse => true %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    
    <style>
    
    </style>
  </head>
  <body>
    <div class="container-fluid">
    <%= render 'layouts/header' %>
      <%= render 'shared/flash_messages' %>
      <%= yield %>
<!--      <%= debug(params) if Rails.env.development? %>-->
    </div>
      <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647; display: block;"><i class="fa fa-angle-up"></i></a>

  </body>
  	
</html>

app/views/pages/amortization.html.erb
    <section class="about" id="about" style="background-color:#fff">
        <div class="container">
            <div class="row">
                <h2 class="col-lg-12 text-center section_header">
                  <hr class="duplicate left visible-desktop ">
                    MONTHLY AMORTIZATION
                  <hr class="duplicate right visible-desktop">
                </h2>
            </div>
            <div class="row faq">
                       
                  <%= render 'amort' %>

        </div>
</section>

app/views/shared/_flash_messages.html.erb
<% unless flash.empty? %>
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> alert-dismissable">
      <a href="#" data-dismiss="alert" class="close">x</a>
      <%= value %>
    </div>
  <% end %>
</div>
<% end %>